### ISSUE TITLE
1.8 Mod auf 1.9 updaten?

### ISSUE THREAD

**Issue by OmegaGolem** [HyCraftHD/Minecraft-Forge-Modding-1.8#1]
Hallo HyCraftHD, ich fragte mich die ganze Zeit wie ich meine Mod von der 1.8 auf die 1.9 updaten kann.
Es ist sehr schade, da ich an dieser gerne weiter machen würde.
Könntest du mir da helfen?

**Comment by HyCraftHD** [comment]
Schau dir dazu einfach die 1.9 Reihe auf meinem Youtubekanal an: https://www.youtube.com/playlist?list=PLyseegEZ84-cwVCHhuDsHJ_Sw3eAZjwey
Wenn etwas nicht klappt beim Updaten, einfach unter einem Video einen Kommentar da lassen oder hier das Issue wieder öffnen!
